baseURL = "https://www.zrzka.dev/"
languageCode = "en-us"
title = "Robert Vojta (𝒵𝓇𝓏𝓀𝒶)"
description = "foo"
googleAnalytics = "UA-110967877-1"

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
post = "/:title"
pages = "/:title"
